config/routes.rb
Rails.application.routes.draw do
  get 'scripts/:guid.sh', controller: 'scripts', action: 'sh'
  get 'scripts/wrapped/:guid.sh', controller: 'scripts', action: 'wrapped_sh', as: :wrapped_sh
  get 'scripts/grep/:id', controller: 'scripts', action: 'grep', as: :grep
  get 'scripts/search', controller: 'scripts', action: 'search', as: :search
  get 'scripts/:id/logs.csv', controller: 'scripts', action: 'csv', as: 'logs_csv'
  resources :scripts

  get 'hosts', controller: 'hosts', action: 'index', as: :hosts
  get 'hosts/:hostname', controller: 'hosts', action: 'show', hostname: /.+/, as: :host

  root 'top#index'

  resources :logs
  post 'scripts/:guid/log', controller: 'logs', action: 'create'
  post 'scripts/archive/:id', controller: 'scripts', action: 'archive', as: :archive_script
  post 'scripts/unarchive/:id', controller: 'scripts', action: 'unarchive', as: :unarchive_script

  devise_for :users, controllers: { omniauth_callbacks: 'authentication' }
  devise_scope :user do
    get 'sign_in', to: 'authentication#login', as: :new_user_session
    delete 'sign_out', to: 'authentication#logout', as: :destroy_user_session
  end

  get '*not_found' => 'application#render_404', constraints: ->(req) do
    req.path.exclude? 'rails/active_storage'
  end
end

app/controllers/hosts_controller.rb
class HostsController < ApplicationController
  def index
    @hosts = Log.all_hosts
  end

  def show
    @hostname = params[:hostname]
    @logs = Log.by_host(@hostname)
  end
end

app/views/hosts/index.html.haml
- content_for :title do
  = t(:title_hosts)

.page-title
  %h3= t(:title_hosts)
  .page-title-right-menu.text-muted
    = @hosts.length
    = t(:hosts_count)

%table.table.table-striped.mt-2
  %thead
    %tr
      %th= t(:field_host)
  %tbody
    - @hosts.each do |host|
      %tr
        %td= link_to host, host_path(host)

app/views/hosts/show.html.haml
- content_for :title do
  = @hostname

%nav{"aria-label" => "breadcrumb"}
  %ol.breadcrumb
    %li.breadcrumb-item
      = link_to t(:title_hosts), hosts_path
    %li.breadcrumb-item.active{"aria-current" => "page"}= @hostname

.page-title
  %h4= @hostname
  .page-title-right-menu.text-muted
    = @logs.length
    = t(:logs_count)

%table.table.table-striped.mt-2
  %thead
    %tr
      %th= t(:field_script_name)
      %th= t(:field_created)
  %tbody
    - @logs.each do |log|
      %tr
        %td= link_to log.script.name, script_path(log.script.id)
        %td= link_to log.formatted_created_at, log_path(log.id)