config/routes.rb
Rails.application.routes.draw do
  get 'scripts/:guid.sh', controller: 'scripts', action: 'sh'
  get 'scripts/wrapped/:guid.sh', controller: 'scripts', action: 'wrapped_sh', as: :wrapped_sh
  get 'scripts/grep/:id', controller: 'scripts', action: 'grep', as: :grep
  get 'scripts/search', controller: 'scripts', action: 'search', as: :search
  get 'scripts/:id/logs.csv', controller: 'scripts', action: 'csv', as: 'logs_csv'
  resources :scripts

  get 'hosts', controller: 'hosts', action: 'index', as: :hosts
  get 'hosts/:hostname', controller: 'hosts', action: 'show', hostname: /.+/, as: :host

  root 'top#index'

  resources :logs
  post 'scripts/:guid/log', controller: 'logs', action: 'create'
  post 'scripts/archive/:id', controller: 'scripts', action: 'archive', as: :archive_script
  post 'scripts/unarchive/:id', controller: 'scripts', action: 'unarchive', as: :unarchive_script

  devise_for :users, controllers: { omniauth_callbacks: 'authentication' }
  devise_scope :user do
    get 'sign_in', to: 'authentication#login', as: :new_user_session
    delete 'sign_out', to: 'authentication#logout', as: :destroy_user_session
  end

  get '*not_found' => 'application#render_404', constraints: ->(req) do
    req.path.exclude? 'rails/active_storage'
  end
end

app/models/log.rb
class Log < ApplicationRecord
  include SlackNotify

  belongs_to :script

  before_save :set_result_bytes

  scope :by_host, lambda {|host|
    where(host: host).order(created_at: :desc)
  }

  scope :select_without_result, -> { select(Log.column_names.reject { |c| c == 'result' }) }

  def formatted_created_at
    return self.created_at.strftime("%Y-%m-%d %H:%M:%S") if self.created_at
    ''
  end

  def self.all_hosts
    self.distinct.order(:host).pluck(:host)
  end

  def as_csv_row
    [host, formatted_created_at, number_to_human_size(result_bytes)]
  end

  private

  def set_result_bytes
    self.result_bytes = self.result&.size || 0
  end
end

app/controllers/logs_controller.rb
class LogsController < ApplicationController
  before_action :set_log, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: [:create]
  skip_before_action :verify_authenticity_token, only: [:create]

  # GET /logs/1
  def show
  end

  # POST /logs
  def create
    if params[:log_file].nil?
      render json: {message: "log file not specified"}.to_json, status: 500
      return
    end

    @log = Log.new(host: params[:host], result: params[:log_file].read)
    script = Script.where(guid: params[:guid]).first
    unless script
      render json: {message: "scripts not found. GUID: #{params[:guid]}"}.to_json, status: 500
      return
    end

    script.logs << @log

    respond_to do |format|
      if @log.save
        format.html { render plain: "log registration successful\n", status: :created}
      else
        format.html { render plain: "log registration failure\n", status: 500 }
      end
    end
  end

  def edit
  end

  def update
    @log.memo = params[:log][:memo]
    @log.save
    redirect_to log_path
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_log
    @log = Log.find(params[:id])
  end
end

app/views/logs/edit.html.haml
- content_for :title do
  = "#{@log.script.name} - #{t(:title_log)} - #{t(:title_edit)}"

%nav{"aria-label" => "breadcrumb"}
  %ol.breadcrumb
    %li.breadcrumb-item
      = link_to t(:title_scripts), scripts_path
    %li.breadcrumb-item
      = link_to @log.script.name, script_path(@log.script)
    %li.breadcrumb-item.active{"aria-current" => "page"}= t(:title_log)

%h3= t(:title_log)

= form_for @log do |f|
  %dl.row
    %dt.col-sm-3.text-right= t(:field_host)
    %dd.col-sm-9= @log.host

    %dt.col-sm-3.text-right= t(:field_uploaded)
    %dd.col-sm-9= @log.formatted_created_at

    %dt.col-sm-3.text-right= t(:field_log)
    %dd.col-sm-9
      %pre= @log.result

    %dt.col-sm-3.text-right= t(:field_log_size)
    %dd.col-sm-9= number_to_human_size @log.result_bytes

    %dt.col-sm-3.text-right= t(:field_memo)
    %dd.col-sm-9
      = f.text_area :memo, class: 'form-control script-area', rows: 15
      .mt-3
        = f.submit t(:button_save), class: 'btn btn-primary', data: { loading_text: 'Loading...' }

app/views/logs/show.html.haml
- content_for :title do
  = "#{@log.script.name} - #{t(:title_log)}"

%nav{"aria-label" => "breadcrumb"}
  %ol.breadcrumb
    %li.breadcrumb-item
      = link_to t(:title_scripts), scripts_path
    %li.breadcrumb-item
      = link_to @log.script.name, script_path(@log.script)
    %li.breadcrumb-item.active{"aria-current" => "page"}= t(:title_log)

.page-title
  %h3= t(:title_log)
  .page-title-right-menu
    = link_to t(:button_edit), edit_log_path, class: 'btn btn-outline-secondary'

%dl.row
  %dt.col-sm-3.text-right= t(:field_host)
  %dd.col-sm-9= @log.host

  %dt.col-sm-3.text-right= t(:field_uploaded)
  %dd.col-sm-9= @log.formatted_created_at

  %dt.col-sm-3.text-right= t(:field_log)
  %dd.col-sm-9
    %pre= @log.result

  %dt.col-sm-3.text-right= t(:field_log_size)
  %dd.col-sm-9= number_to_human_size @log.result_bytes

  %dt.col-sm-3.text-right= t(:field_memo)
  %dd.col-sm-9
    - unless @log.memo.blank?
      %pre= @log.memo